### ISSUE TITLE
API KEY WEB SERVER DOWN

### ISSUE THREAD

**Issue by VirtusHostiz** [nullworks/accgen-web#33]
Api key Port website: 2053 is down since yesterday afternoon :(
![Screenshot_4](https://user-images.githubusercontent.com/34197859/56358371-cd6d2300-61b4-11e9-806d-20de6b75c84e.png)

**Comment by BenCat07** [comment]
You have been sent this message via Telegram already:
Hello API Key owner!
We will be terminating port 2053 of the API after 17.04.2019 (DD.MM.YYYY)
In the future you should use accgen.cathook.club as the API domain. It is highly recommended to use HTTPS instead of HTTP.
The format for the new API URL: `https://accgen.cathook.club/api/v1/account/[your_key_here]`
