### ISSUE TITLE
P A T R E O N 

### ISSUE THREAD

**Issue by Falghere** [nullworks/accgen-web#92]
Hello, I'd like to buy some accounts ... can any of the moderators here sell me some accounts? I would like to buy some...

//other thing

if I turn patreon ... I gain access to an API?

**Comment by SylveonBottle** [comment]
If you connect SAG to your patreon, you can become a patreon for $1 to unlock custom generator options, and gain access to the patreon-only telegram.

**Comment by Falghere** [comment]
I know this, but I want to know if I pay PATREON I gain access to an API or not ...

**Comment by SylveonBottle** [comment]
> I know this, but I want to know if I pay PATREON I gain access to an API or not ...

API was removed due to Steam's newly implemented Recatcha V2. You now must manually create individual accounts, but you can still do that insanely faster with accgen.cathook.club. Even more faster with the patreon options.

Sadly if you want a massive bulk of accounts you're going to have to buy them off of someone, I think.

**Comment by Ashesh3** [comment]
We don't sell accounts and api is no longer functional.
